apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chatplan-storage
  namespace: pts-2026-rictjo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: rook-ceph-rbd
